# Generated by Django 3.0.1 on 2019-12-28 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_employer'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='focal_person',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='focal_person_contact',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='focal_person_email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
